name: Deploy
on:
  push:
    tags:
      - "**"
    branches-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          separator: "/"
          msg: ${{github.ref_name}}
      - name: Set envs
        run: echo "APP_NAME=${{ steps.split.outputs._0 }}" >> $GITHUB_ENV
          echo "APP_TAG=${{ steps.split.outputs._1 }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: make deps

      - name: Build
        run: make build

      - name: Deploy
        run: echo "Deploying ${{ env.APP_NAME }} with tag ${{ env.APP_TAG }}"
